- frontend/src/styles/_breakpoints.scss
- Adiciona o arquivo `_breakpoints.scss` com os breakpoints de responsividade
- Pra implementar: importe o arquivo com os breakpoints (`import "~styles/breakpoints"`) e pra usar o mixin (`@include tablet-landscape { color: purple }`)
> Adiciona breakpoints de responsividade

- README.md
- backend/app.js
- backend/src/app.js
- backend/src/controllers/userController.js
- backend/src/repository/models/user.js
- backend/src/repository/mongo.js
- docker-compose.yml
* Integração com mongoose
* Mock api de registro de usuários.
* Atualização do README para uso do mongo no backend
* Remoção do arquivo `src/app.js` dado que era código boilerplate que não fazia nada
*Observação:* o modelo de User não é o modelo final, apenas usado para fins de testes.
> Integração com mongoose e mock de API para registro de usuários.

- frontend/public/index.html
- frontend/src/App.js
- frontend/src/components/Button/Button.js
- frontend/src/components/Button/Button.module.scss
- frontend/src/components/Container/Container.js
- frontend/src/components/Container/Container.module.scss
- frontend/src/components/Footer/Footer.js
- frontend/src/components/Footer/Footer.module.scss
- frontend/src/components/SideBar/SideBar.js
- frontend/src/components/SideBar/SideBar.module.scss
- frontend/src/components/SideBarItem/SideBarItem.js
- frontend/src/components/SideBarItem/SideBarItem.module.scss
- frontend/src/hooks/useHover.js
- frontend/src/styles/index.css
- frontend/src/views/Home/Home.js
- frontend/src/views/Home/Sections/Landing/Landing.js
- frontend/src/views/Home/Sections/Landing/Landing.module.scss
- Cria componentes Button (a ser adicionados mais variações), Container, SideBar e Footer
- Cria seção Landing
- Cria Home view
- Adiciona variáveis CSS para tamanhos de fonte
- Cria hook useHover
> Adiciona seção Landing

- frontend/src/App.js
- frontend/src/components/Card/Card.module.scss
- frontend/src/components/SideBar/SideBar.js
- frontend/src/components/SideBar/items.js
- frontend/src/components/SideBarItem/SideBarItem.js
- frontend/src/components/Tag/Tag.js
- frontend/src/components/Tag/Tag.module.scss
- frontend/src/styles/index.css
- frontend/src/views/Home/Sections/WhatDo/WhatDo.js
- frontend/src/views/Home/Sections/WhatDo/WhatDo.module.scss
- frontend/src/views/Quarantine/Quarantine.js
- frontend/src/views/Quarantine/Quarantine.module.scss
- Adiciona página QuarentenALES (acessível pela rota /quarentenales e com dado mockado por enquanto)
- Adiciona o componente Tag
- Generaliza um pouco mais o componente Card
> Página QuarentenALES

- backend/src/repository/models/class.js
- backend/src/repository/models/subject.js
- backend/src/repository/models/teacher.js
- backend/src/repository/models/user.js
Regarding issues #19,  #20, #21
> Added schema for Teacher, Subject and Class entities

- frontend/src/App.js
- frontend/src/components/Card/Card.module.scss
- frontend/src/components/Input/Input.js
- frontend/src/views/Course/CourseDetail/CourseDetail.js
- frontend/src/views/Course/CourseDetail/CourseDetail.module.scss
- frontend/src/views/Course/CourseEdit/CourseEdit.js
- frontend/src/views/Course/CourseEdit/CourseEdit.module.scss
- frontend/src/views/Course/CourseList/CourseList.js
- frontend/src/views/Course/CourseList/CourseList.module.scss
- frontend/src/views/Course/CourseNew/CourseNew.js
- frontend/src/views/Course/CourseNew/CourseNew.module.scss
- frontend/src/views/Home/Sections/WhatDo/WhatDo.module.scss
- frontend/src/views/Login/Login.module.scss
- frontend/src/views/MyArea/MyArea.js
- frontend/src/views/MyArea/MyArea.module.scss
- frontend/src/views/MyArea/items.js
- frontend/src/views/NewPassword/NewPassword.module.scss
- frontend/src/views/Profile/Profile.js
- frontend/src/views/Quarantine/Quarantine.module.scss
- frontend/src/views/ResetPassword/ResetPassword.module.scss
- Adiciona as views `CourseList`, `CourseNew`, `CourseEdit` e `CourseDetail`
- Refatora estilos do componente `Card` e props do componente `Input`
> Adiciona fluxo pra listar, criar e editar matérias

- backend/app.js
- backend/package.json
- backend/src/logger/index.js
- deploy/docker-compose.yml
* Cria dois loggers, um para erro e outro para todos os outros niveis
* Por hora concatena tudo em arquivos fixos, posteriormente podemos fazer uma rotação de logs
> [backend] Logging para a api

- .github/pull_request_template.md
Template de PR baseado nesse aqui.
É bem parecido com o que eu uso no meu trabalho, e lá funciona bem. Mas acho válido remover/adicionar o que for necessário.
https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/
> Adiciona template de PR

- .vscode/settings.json
- frontend/src/components/ButtonIcon/ButtonIcon.module.scss
- frontend/src/routes/router.js
- frontend/src/routes/routes.js
- frontend/src/services/lesson.service.js
- frontend/src/styles/index.css
- frontend/src/views/Course/CourseDetail/CourseDetail.js
- frontend/src/views/Course/CourseDetail/CourseDetail.module.scss
- frontend/src/views/Lesson/LessonNew/LessonNew.js
- frontend/src/views/Lesson/LessonNew/LessonNew.module.scss
Este PR (#82) adiciona a funcionalidade de criar aulas pra uma determinada matéria. Ao acessar a página de detalhe de uma matéria, é possível clicar no botão pra adicionar uma nova aula, o que deve te redirecionar a uma nova página onde será possível adicionar os dados da nova aula. Em caso de sucesso, o usuário é retornado pra página da matéria e a nova aula deve aparecer na lista de aulas. No caso de erro, um _toast_ com uma mensagem de erro deve aparecer e não deve haver redirecionamento.
Supondo uma matéria já adicionada, acessa a página desta e clique no botão "Adicionar Aula". Após ser redirecionado, preencha o forms com os dados necessários e clique em "Enviar". Em caso de sucesso, o usuário deve ser redirecionado de volta pra página da matéria e a aula deve aparecer na lista de …
> UI Criação de Aulas

- backend/src/middlewares/auth.middleware.js
As mudanças deste PR evitam que os middlewares continuam executando nas situações em que o JWT expirou. Antes, os middlewares continuavam a executar (desnecessariamente) e crashavam a API.
Coloque o tempo baixo de expiração do _token_ e _refresh-token_ para poder testar (10 e 30 segundos, por exemplo). Suba a UI, faça login, interaja e veja se o token é renovado corretamente e a sessão é expirada quando o refresh-token expira.
> Arruma erro dos middlewares de autenticação

- backend/src/controllers/course.controller.js
- backend/src/controllers/lesson.controller.js
- backend/src/models/course.js
- backend/src/models/lesson.js
- backend/src/services/course.service.js
- frontend/src/services/lesson.service.js
- frontend/src/views/Course/CourseDetail/CourseDetail.js
- frontend/src/views/Lesson/LessonNew/LessonNew.js
- frontend/src/views/Professor/ProfessorEnroll/ProfessorEnroll.js
- Remodelagem do relação `Course <-> Lesson`. Antes `Lesson` possuía um campo `course` com a referência da matéria e agora `Course` contém um array de referências pras aulas.
- Adequação das telas de detalhe de curso e adição de aula de acordo com a mudança na API
- Fix da renderização dos dados do `Dropdown` e validação da data de aniversário (ambos na tela de cadastro de professor)
Apenas simular o fluxo de visualizar a lista de aulas de uma matéria, adicionar e remover aulas de uma matéria.
E também simular o fluxo de cadastro de professor.
> Refatoração da relação entre os modelos Course/Lesson

- backend/app.js
- backend/src/controllers/auth.controller.js
- backend/src/controllers/course.controller.js
- backend/src/controllers/index.js
- backend/src/controllers/lesson.controller.js
- backend/src/controllers/mail.controller.js
- backend/src/controllers/password.controller.js
- backend/src/controllers/professor.controller.js
- backend/src/controllers/user.controller.js
- frontend/src/services/api.js
- frontend/src/services/auth.service.js
- frontend/src/services/lesson.service.js
- frontend/src/services/mail.service.js
- frontend/src/services/professor.service.js
- frontend/src/services/user.service.js
Este PR refatora os todos os _controllers_ da API, sendo estes agora referenciados no `index.js`, deixando o `app.js` mais clean.
Além disso, alguns endpoints foram movidos de arquivo por questões semânticas e pra reforçar a consistência do path dos endpoints. Foram feitos os ajustes necessários no `frontend` e no `Postman`.
Basicamente simular os fluxos envolvidos e verificar se tudo está funcionando corretamente.
> Refatoração dos controllers na API

- frontend/src/views/Profile/Profile.js
Fix da renderização da data no componente `<DateInput>`. Anteriormente estava crashando a UI quando retornava `null`.
Apenas simular o fluxo de login e visualização do perfil, alterando a data de aniversário, por exemplo.
> fix: birthday validation in Profile view

- .github/workflows/ci.yaml
- README.md
- backend/src/controllers/mail.controller.js
- backend/src/controllers/password.controller.js
- backend/src/controllers/professor.controller.js
- docker-compose.ci.yml
- docker-compose.test.yml
- Adiciona o arquivo `.github/workflows/ci.yml` contendo as especificações e política de integração contínua
- Adiciona arquivo `docker-compose.ci.yml` para ser utilizado no ambiente de integração contínua
- Impede que processamento de email sejam feitos ao rodar os testes (dado os limites de execução destes)
A documentação foi atualizada com os passos para rodar os testes localmente e também explica sobre as pipelines do Github Actions.
> Configuração do CI

- .github/workflows/ci.yaml
- docker-compose.ci.yml
- Separa o fluxo do CI em 2 _jobs_: `build` e `test`
> Separação do fluxo do CI em 2 passos

- frontend/package.json
- frontend/src/App.css
- frontend/src/App.js
- frontend/src/routes/router.js
- frontend/src/routes/routes.js
- frontend/src/services/recruitment.service.js
- frontend/src/views/Home/Sections/Landing/Landing.module.scss
- frontend/src/views/Home/Sections/Recruitment/Recruitment.module.scss
- frontend/src/views/MyArea/items.js
- frontend/src/views/Recruitment/ProcessEdit/ProcessEdit.js
- frontend/src/views/Recruitment/ProcessEdit/ProcessEdit.module.scss
- frontend/src/views/Recruitment/ProcessNew/ProcessNew.js
- frontend/src/views/Recruitment/ProcessNew/ProcessNew.module.scss
- frontend/src/views/Recruitment/Recruitment.js
- frontend/src/views/Recruitment/Recruitment.module.scss
- Adiciona `antd` e `moment` como dependências
- Integra os fluxos de listagem, criação, edição, encerramento e arquivamento de processos de recrutamento
Apenas simular os fluxos citados acima. Testes de API já foram inclusos no #101
> CRUD de Processos de Recrutamento (UI)

- backend/src/controllers/__tests__/recruitment.controller.test.js
- backend/src/controllers/recruitment.controller.js
- backend/src/helpers/status.js
- backend/src/models/__tests__/interview.test.js
- backend/src/models/__tests__/recruitment.test.js
- backend/src/models/interview.js
- backend/src/models/recruitment.js
- backend/src/services/__tests__/interview.service.test.js
- backend/src/services/__tests__/recruitment.service.test.js
- backend/src/services/interview.service.js
- backend/src/services/recruitment.service.js
- Adiciona model `Interview`
- Um processo de recrutamento possui uma lista de `interviews`
- Adiciona _services_ e _endpoint_ para adicionar entrevistas em um processo de recrutamento
- Foram adicionados testes unitários e de integração para as novas funcionalidades
> Adiciona modelo Interview

- backend/src/helpers/status.js
- backend/src/models/recruitment.js
- frontend/src/views/Recruitment/Recruitment.js
- Remove o status `archived` do model `Recruitment`
- Refatora UI e API para lidar apenas com os status: `active` e `done`
Resolve #104
> #104 Refactor do status de processos de recrutamento

- RECRUITMENT.md
- backend/.gitignore
- backend/package.json
- backend/src/calendar/calendar.js
- backend/src/calendar/googleAuth.js
- backend/src/calendar/services/__tests__/createCalendar.test.js
- backend/src/calendar/services/__tests__/editCalendar.test.js
- backend/src/calendar/services/createCalendar.js
- backend/src/calendar/services/editCalendar.js
- backend/src/controllers/__tests__/recruitment.controller.test.js
- backend/src/controllers/recruitment.controller.js
- backend/src/models/__tests__/recruitment.test.js
- backend/src/models/recruitment.js
- backend/src/services/__tests__/recruitment.service.test.js
- frontend/src/routes/router.js
- frontend/src/routes/routes.js
- frontend/src/views/Recruitment/Instructions/Instructions.js
- frontend/src/views/Recruitment/Instructions/Instructions.module.scss
- frontend/src/views/Recruitment/Instructions/steps.js
- frontend/src/views/Recruitment/ProcessNew/ProcessNew.js
- Adiciona a dependência `googleapis`
- Configura o client do Calendar
- Integra a criação/edição de um calendário quando um novo processo de recrutamento é criado/editado
- Adiciona instruções de como prosseguir após o processo de recrutamento é criado 
Resolve #109 
Seguir os passos descritos no documento `RECRUITMENT.md` e simular o fluxo de criação e edição de um processo de recrutamento.
> Integração com API do Google Calendar

- backend/src/calendar/helpers/__tests__/addStatistics.test.js
- backend/src/calendar/helpers/__tests__/separateByDays.test.js
- backend/src/calendar/helpers/addStatistics.js
- backend/src/calendar/helpers/separateByDays.js
- backend/src/controllers/recruitment.controller.js
- frontend/src/views/Home/Home.js
- frontend/src/views/Home/Sections/Subscription/Subscription.js
- frontend/src/views/Home/Sections/Subscription/Subscription.module.scss
- frontend/src/views/Recruitment/ProcessDetail/ProcessDetail.js
- frontend/src/views/Recruitment/ProcessDetail/ProcessDetail.module.scss
- frontend/src/views/Recruitment/ProcessDetail/popover.js
Resolve #112 
- Arruma estilos da seção `Subscription` da `Home` (e renomeia arquivos)
- Adiciona seção de estatísticas na página de detalhe de processo de recrutamento
- Padroniza formato de datas dos eventos (agora `dd/mm/aaaa` com `dd` e `mm` sempre com 2 dígitos)
- Simular visualização da respectiva tela
- Novos testes foram adicionados
> Adiciona estatísticas básicas de um processo de recrutamento

- .github/workflows/cd.yml
Resolve #115 
- Adiciona configuração para deploy automático assim que um `Pull Request` pra `master` é aprovado
> Configura deploy contínuo

- .github/workflows/ci.yaml
- Apenas remove `secrets` não necessários para rodar o fluxo de testes
> Remove secrets desnecessários para o fluxo de integração contínua

- frontend/src/views/Home/Sections/About/About.js
> Remoção dos logos da Unicamp e da ProEC

- frontend/src/components/SideBar/items.js
- frontend/src/routes/router.js
- frontend/src/routes/routes.js
- frontend/src/views/Aluno/Aluno.js
- frontend/src/views/Aluno/Aluno.module.scss
- frontend/src/views/Volunteer/Volunteer.js
- frontend/src/views/Volunteer/Volunteer.module.scss
> Modificações na reunião 25/03/2021

- README_pt-br.md
- RECRUITMENT.md
- Adiciona um `README` em Português
- Atualiza documentação sobre integração do Processo Seletivo
> Docs: Adiciona README em PT-BR

- frontend/src/views/Aluno/Aluno.js
- frontend/src/views/Aluno/Aluno.module.scss
- frontend/src/views/Volunteer/Volunteer.js
- frontend/src/views/Volunteer/Volunteer.module.scss
> Revisão do design das páginas Aluno e Volunteer

- docker-stack.yml
Adiciona o arquivo `docker-stack.yml` que serve para subir os serviços em ambiente de produção.
> Adiciona arquivo docker-stack.yml

- .github/dependabot.yml
Remoção do arquivo `dependabot.yml`
> fix: remove dependabot file

- frontend/public/index.html
- frontend/src/views/Home/Sections/Testimonials2/Testimonials2.js
> Adição dos depoimentos

- frontend/public/index.html
> Tamanho da caixa de depoimentos aumentada

- frontend/src/views/Home/Home.js
> remoção do texto do PS2021_2 do site

- frontend/src/views/Home/Home.js
> alterado seção home removido PS

- frontend/src/components/SideBar/items.js
- frontend/src/views/Contact/Contact.js
- frontend/src/views/Home/Sections/WhatDo/WhatDo.module.scss
- frontend/src/views/Home/Sections/WhatDo/activities.js
- frontend/src/views/Home/Sections/WhatDo/courses.js
- frontend/src/views/Home/Sections/WhatIs/WhatIs.module.scss
> modificações reunião 09nov
